# Copyright (c) 2026 ADBC Drivers Contributors
# Copyright (c) 2026 Query Farm LLC
# SPDX-License-Identifier: Apache-2.0
line-length = 120
target-version = "py313"

[lint]
select = ["E", "F", "I", "UP", "B", "SIM", "D"]

[lint.pydocstyle]
convention = "google"
